{% set version = "3.0-6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-car
  version: {{ version|replace("-", "_") }}

source:
  fn: car_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/car_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/car/car_{{ version }}.tar.gz
  sha256: 669d15fa609f74f84758ca68981b91860fc93ee815a492745cb97aa014af657b

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-abind
    - r-cardata >=3.0_0
    - r-lme4
    - r-maptools
    - r-mgcv
    - r-nlme
    - r-nnet
    - r-pbkrtest >=0.4_4
    - r-quantreg
    - r-rio
  run:
    - r-base
    - r-mass
    - r-abind
    - r-cardata >=3.0_0
    - r-lme4
    - r-maptools
    - r-mgcv
    - r-nlme
    - r-nnet
    - r-pbkrtest >=0.4_4
    - r-quantreg
    - r-rio

test:
  commands:
    - $R -e "library('car')"           # [not win]
    - "\"%R%\" -e \"library('car')\""  # [win]

about:
  home: https://r-forge.r-project.org/projects/car/, https://CRAN.R-project.org/package=car,
    http://socserv.socsci.mcmaster.ca/jfox/Books/Companion/index.html
  license: GPL (>= 2)
  summary: ' Functions to Accompany J. Fox and S. Weisberg,  An R Companion to Applied Regression,
    Third Edition, Sage, in press.'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
