{% set version = "3.1-2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-car
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/car_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/car/car_{{ version }}.tar.gz
  sha256: 89263491977ac8e9406b2f4b1638bf06c7ddd1b0e0e3ecda4be61420474674c8

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-abind
    - r-cardata >=3.0_0
    - r-lme4
    - r-maptools
    - r-mgcv
    - r-nlme
    - r-nnet
    - r-pbkrtest >=0.4_4
    - r-quantreg
    - r-rio
  run:
    - r-base
    - r-mass
    - r-abind
    - r-cardata >=3.0_0
    - r-lme4
    - r-maptools
    - r-mgcv
    - r-nlme
    - r-nnet
    - r-pbkrtest >=0.4_4
    - r-quantreg
    - r-rio

test:
  commands:
    - $R -e "library('car')"           # [not win]
    - "\"%R%\" -e \"library('car')\""  # [win]

about:
  home: https://r-forge.r-project.org/projects/car/, https://CRAN.R-project.org/package=car, http://socserv.socsci.mcmaster.ca/jfox/Books/Companion/index.html
  license: GPL-2.0-or-later
  summary: Functions to Accompany J. Fox and S. Weisberg, An R Companion to Applied Regression, Third Edition, Sage, 2019.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: car
# Version: 3.0-6
# Date: 2019-12-20
# Title: Companion to Applied Regression
# Authors@R: c(person("John", "Fox", role = c("aut", "cre"), email = "jfox@mcmaster.ca"), person("Sanford", "Weisberg", role = "aut", email = "sandy@umn.edu"), person("Brad", "Price", role = "aut", email = "brad.price@mail.wvu.edu"), person("Daniel", "Adler", role="ctb"), person("Douglas", "Bates", role = "ctb"), person("Gabriel", "Baud-Bovy", role = "ctb"), person("Ben", "Bolker", role="ctb"), person("Steve", "Ellison", role="ctb"), person("David", "Firth", role = "ctb"), person("Michael", "Friendly", role = "ctb"), person("Gregor", "Gorjanc", role = "ctb"), person("Spencer", "Graves", role = "ctb"), person("Richard", "Heiberger", role = "ctb"), person("Pavel", "Krivitsky", role = "ctb"), person("Rafael", "Laboissiere", role = "ctb"), person("Martin", "Maechler", role="ctb"), person("Georges", "Monette", role = "ctb"), person("Duncan", "Murdoch", role="ctb"), person("Henric", "Nilsson", role = "ctb"), person("Derek", "Ogle", role = "ctb"), person("Brian", "Ripley", role = "ctb"), person("William", "Venables", role = "ctb"), person("Steve", "Walker", role="ctb"), person("David", "Winsemius", role="ctb"), person("Achim", "Zeileis", role = "ctb"), person("R-Core", role="ctb"))
# Depends: R (>= 3.5.0), carData (>= 3.0-0)
# Imports: abind, MASS, mgcv, nnet, pbkrtest (>= 0.4-4), quantreg, grDevices, utils, stats, graphics, maptools, rio, lme4, nlme
# Suggests: alr4, boot, coxme, leaps, lmtest, Matrix, MatrixModels, rgl (>= 0.93.960), sandwich, SparseM, survival, survey
# ByteCompile: yes
# LazyLoad: yes
# Description: Functions to Accompany J. Fox and S. Weisberg, An R Companion to Applied Regression, Third Edition, Sage, 2019.
# License: GPL (>= 2)
# URL: https://r-forge.r-project.org/projects/car/, https://CRAN.R-project.org/package=car, http://socserv.socsci.mcmaster.ca/jfox/Books/Companion/index.html
# Author: John Fox [aut, cre], Sanford Weisberg [aut], Brad Price [aut], Daniel Adler [ctb], Douglas Bates [ctb], Gabriel Baud-Bovy [ctb], Ben Bolker [ctb], Steve Ellison [ctb], David Firth [ctb], Michael Friendly [ctb], Gregor Gorjanc [ctb], Spencer Graves [ctb], Richard Heiberger [ctb], Pavel Krivitsky [ctb], Rafael Laboissiere [ctb], Martin Maechler [ctb], Georges Monette [ctb], Duncan Murdoch [ctb], Henric Nilsson [ctb], Derek Ogle [ctb], Brian Ripley [ctb], William Venables [ctb], Steve Walker [ctb], David Winsemius [ctb], Achim Zeileis [ctb], R-Core [ctb]
# Maintainer: John Fox <jfox@mcmaster.ca>
# Repository: CRAN
# Repository/R-Forge/Project: car
# Repository/R-Forge/Revision: 617
# Repository/R-Forge/DateTimeStamp: 2019-12-20 14:33:56
# Date/Publication: 2019-12-23 11:10:02 UTC
# NeedsCompilation: no
# Packaged: 2019-12-20 14:50:33 UTC; rforge
