{% set version = "3.0-2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-car
  version: {{ version|replace("-", "_") }}

source:
  fn: car_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/car_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/car/car_{{ version }}.tar.gz
  sha256: df59a9ba8fed67eef5ddb8f92f2b41745df715d5695c71d562d7031513f37c50

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-mass
    - r-mgcv
    - r-nnet
    - r-pbkrtest >=0.4_4
    - r-quantreg
  run:
    - r-base
    - r-mass
    - r-mgcv
    - r-nnet
    - r-pbkrtest >=0.4_4
    - r-quantreg

test:
  commands:
    - $R -e "library('car')"  # [not win]
    - "\"%R%\" -e \"library('car')\""  # [win]

about:
  home: https://r-forge.r-project.org/projects/car/
  license: GPL (>= 2)
  summary: |
    Functions and Datasets to Accompany J. Fox and S. Weisberg, An R Companion to Applied
    Regression, Second Edition, Sage, 2011
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
