appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: D2lbZvsnOKg3bV9U9cB/6AFJfdHBUetUELTQE+vdqjAriYzdCArwDkLLjkurPLRrQ+cRfZebKUI7Ee0TwBxm/cH/SoKSei/1fHTIkTpta359Vy4NYzfDjhD2IYTVIRb3XbL7zu0U/0CvkwPAw3SakcPFSDZc4/OrY53lJ44UwwxR2P1K8HZxvsK/Ike8mq2JkVPz+Hc+dpzr9jYwI0gP20Ia1hNH1SK0eHLF2Ul2eGOapX2f0nrIF5RcQjDfyyKC4ttdOh5Yf81lvbkWymAAtzhhKEh/DJjeqIUYxLhZTyWHHRGY2wdlMYqOC8IYtQkoiLubDpW8O9uLxroqMel/B+vpLr+KQAxsv7ALwv0BU8PtNojAn0egCo3Ap4DVij2mVayZ689Q5XDUvjUYsWr7Xz6lmVEjGRBAaTByeaAPLRYuMHP+hLAjGGjMHT/oCbJqouJN+xLg7N34F9xu9K7UKsHFWhs/2lqKfXTPkwnztEtvG2eUwIOrmMqtxyf9fQejREJ3RwIFI9KXnqtGi6VdwIVo/zwkuBmb3MR2/MtOAIYABSbOYTRkE39Cn/HA0J3bW9K8aGAx50Av6W21L37ddFQQ/ZhwLsoOqRRwcGvi0nKNaNEE7oyDJLWuBrfB4seSLI7zuqk74XLWJmksb/uyXCGj4zkZxLNWg2S4DlAxQMk=}
